### PR TITLE
change license and add git template

### PR DESCRIPTION
**Pull request by sinlov**
have fun

干得漂亮！

### CODE REVIEW

**Comment by Miuzarte** [comment]
这么好的项目怎么会有虫子可以提交呢

**Comment by Pure-Peace** [comment]
非常好！符合项目我们伟大的愿景！并且这是来自社区的第一个PR，掌声！

**Comment by jhonnybail** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
raymondtharris, @michaelscheung, @koszyczek, @mattia-hash, @AnthonyOkoth00, @hyysguyang, @newsam18, @jffernandez, @qinjianxyz, @givingwu, @SugarHeartEgg, @ArthurTavaresBezerra, @v1otusc, @muturgan, @timsntech, @oudommeas, @jgonggrijp, @SagiSatish, @cristianireyes, @Ilingu, @57-Wolve, @wangjiangs, @BilalMir135, @EscapeCharacter-dev, @cepnijanasa, @stevebaros, @Lamhoiyan, @tobey0x, @amusingaxl, @masteryi-0018, @starbt, @adibmed, @dojo-vue, @TopLiu, @iPaulPro, @ramsarthe, @sherry0319, @lin-xii, @anirudhXshetty, @kmiyachi, @tushar-asodariya, @epilept1ck, @soekchl, @AnthonyAltieri, @stellarnode, @thorn-harvestar, @GiorgioMegrelli, @BiggerBen13, @EightBitBoy, @evaleriesSilvrbckw, @yokinist, @fakemonkgin, @skellet0r, @cernak, @Gexla, @viper-00, @jdbender66, @vfishv, @lynnsir-102, @simonKristensen, @azigler, @tylerwince, @indegro, @itgoyo, @nicolas-law, @asimsheikh, @allenlooplee, @Hamza442004, @samever7, @longhoangwkm, @mjmiles11, @theideasaler, @jeswinsimon, @guzmonne, @StanleyH-915, @vefghmhassan, @pasevin, @frankdev7, @Saka7, @sherryoung1028, @malixsys, @afneville, @simonholm, @emilypmendez, @5vg, @pcy190, @samwell9624, @zlhwdsz, @ahmedSalama101, @Debopom-Banerjee, @austinkettner, @boxcee, @shlokgilda, @kwedrowicz, @lerajk, @ezesiza, @bmccaf10, @pjmalandrino, @mustardfrog

**Comment by tychiadet** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
kruthika9, @1blockologist, @zikosw, @yuliwilliam, @banteg, @jamshidi799, @ncitron, @nmakhotkin, @xiashali, @0xkeider, @LexPrime, @adembyon, @0xTux, @sunliwen, @rcoyner, @gengmoqi, @shexinyi, @ThomasErhel, @eth2devops, @liwuv587, @raho1, @JupiterEight, @Cyberdevil112, @the-tech-girl-frema, @LeoHChen, @Trevillie, @ronaldkohhh, @ajanuar, @L-Kov, @riptl, @Double1996, @kalbhairavaa, @gsscoder, @dewedeth, @tuncatunc, @vinhloc30796, @xJonathanLEI, @joleeee, @6, @imkk000, @somewheel, @leodsoft, @x2ice, @DiveInto, @treethought, @AllanM007, @estensen, @joshstevens19, @EvanfanBao, @Pnkjgot01haskel, @d333m000, @nflaig, @BenedettiLucca, @0xprincess, @defi-degaulle, @nytzuga, @hillhero789, @0x19dG87, @buzs, @MisakaCenter, @vetri02, @mistakia, @cyborgdennett, @akhilmantha, @chaowh, @weipin, @balikanlimahmut, @arberx, @myiwen, @cannium, @MysticRyuujin, @0xcaff, @fly51fly, @onesecurity, @CactusByte, @qdzzyb2014, @uniyalabhishek, @BluePositive, @Okemwag, @dankostiuk, @tuxcanfly, @bout3fiddy, @AndreaB-28, @wmbonfiglio, @J1a-wei, @JingwenTian, @mgladson, @radkomih, @Code-Hex, @reg2005, @shyam-patel-kira, @Cyberdevil112, @sokel, @sam-potter, @0xabhinav, @miguelmtzinf, @faith0811, @andrewpedia, @bmann

**Comment by GitSyncPromedia** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
daneoshiga, @r1cs, @3ltrashpanda, @rourpab, @ZhangTao1596, @massun-onibakuchi, @zhangtenghai, @czar0, @chopachom, @Guillrmo, @ashablovskiy, @Nvz0x, @Hansum, @feng-sifang, @juancolchete, @nemani, @8adre, @aditya520, @Web3deeper, @durango, @j-greig, @Uniblake, @lojikil, @avalidurl, @0xxfu, @mattiascaricato, @yehezkielgunawan, @sprtd, @terrycryptocom, @epappas, @david942j, @p1v07, @xajkep, @LiamOrrill, @SebastianElvis, @wei3hua2, @kmlbgn, @lazydefi1, @DecentralizedPlanetarian, @fullstackadam, @iLVino, @fabriciosantana, @mmm5609, @izayl, @deadPix3l, @wassname, @harmenx, @bukezhizhi, @wddwycc, @PwnDextercloudfreexiao, @victortv7, @timsntech, @fdisotto, @tangzheng0105, @amusingaxl, @NorthHub, @0-sploit, @zachperez, @Defcon004, @dbsc, @GazimbeIsaac, @eth-skywalker, @aifa, @0xfornax, @moodysalem, @crazy-abc, @elise-ng, @yehezkielgunawan, @PilotDebug, @LouisTsai-Csie, @chihkaiyu, @teknogeek, @0xtomm, @nanyang24, @zhiqiangxu, @descartes100, @zblee, @757566833, @andrebhu, @Jrachman, @michailb, @brefontaire, @libcrack, @tssandor, @amitkot, @daoyuan14, @canonbrother, @xpixpi, @adamhos, @here4thee, @bernestoalberto, @K2, @wphan, @Joyce12123, @hs7558, @kornkutan, @EnbangWu, @ggs134, @China-Chris

**Pull request merged**
